apiVersion: v1
kind: ServiceAccount
metadata:
  name: fitness-app-sa
  namespace: default
  annotations:
    # This Client ID tells Workload Identity which Azure Identity to assume
    # Replace the value below with the Client ID(managed identity)
    azure.workload.identity/client-id: "8ba930df-4f5f-45aa-8fcd-db7be081876d"
  labels:
    azure.workload.identity/use: "true"
